"""Foot target — writes a terminal colour theme to ``~/.config/foot/colors.ini``.

Both light and dark sections are always written so that foot's
``initial-color-theme`` can dynamically switch between them.

After writing, colours are pushed to all active PTY sessions via OSC escape
sequences — running terminals update instantly without a restart.
"""

from __future__ import annotations

import sys
from pathlib import Path

from terratheme.terminal_push import push_from_config

from .base import BaseTarget


_ANSI_TOKENS = [
    ("regular0",  "ansi_0"),
    ("regular1",  "ansi_1"),
    ("regular2",  "ansi_2"),
    ("regular3",  "ansi_3"),
    ("regular4",  "ansi_4"),
    ("regular5",  "ansi_5"),
    ("regular6",  "ansi_6"),
    ("regular7",  "ansi_7"),
    ("bright0",   "ansi_8"),
    ("bright1",   "ansi_9"),
    ("bright2",   "ansi_10"),
    ("bright3",   "ansi_11"),
    ("bright4",   "ansi_12"),
    ("bright5",   "ansi_13"),
    ("bright6",   "ansi_14"),
    ("bright7",   "ansi_15"),
]


def _hex_stripped(hex_str: str) -> str:
    """Strip the leading ``#`` from a hex colour string."""
    return hex_str.lstrip("#")


def _section(lines: list[str], mode: str, colors: dict[str, str]) -> None:
    # Background/foreground use mode-appropriate tokens.
    # ANSI slots (regular0-7, bright0-7) use cross-mode references so that
    # ANSI black/bright-black are always near-black (from dark palette) and
    # white/bright-white are always near-white (from light palette).
    lines.append(f"[colors-{mode}]")
    lines.append(f"background={_hex_stripped(colors['base'])}")
    lines.append(f"foreground={_hex_stripped(colors['standard'])}")
    lines.append(f"selection-background={_hex_stripped(colors['base'])}")
    lines.append(f"selection-foreground={_hex_stripped(colors['standard'])}")
    cursor = f"{_hex_stripped(colors['bottom'])} {_hex_stripped(colors['standard'])}"
    lines.append(f"cursor={cursor}")
    for key, token in _ANSI_TOKENS:
        lines.append(f"{key}={_hex_stripped(colors[token])}")
    lines.append("")


class FootTarget(BaseTarget):
    """Generate ``~/.config/foot/colors.ini`` with both dark and light sections."""

    name = "foot"
    description = "Foot terminal emulator colours"
    output_path = "~/.config/foot/colors.ini"

    def render(self, palette: dict, mode: str) -> str:
        lines: list[str] = [
            "# Generated by terratheme",
            f"# Mode: {mode}",
            "",
            "[main]",
            f"initial-color-theme={mode}",
            "",
        ]

        # Always write both sections so foot can switch modes dynamically
        _section(lines, "dark", palette["dark"])
        _section(lines, "light", palette["light"])

        return "\n".join(lines)

    def write(self, palette: dict, mode: str) -> Path:
        """Render, write to disk, and push colours to all active terminals."""
        path = super().write(palette, mode)
        try:
            push_from_config(path)
            print(f"  [foot] pushed colours to active terminals", file=sys.stderr)
        except (FileNotFoundError, ValueError, OSError) as exc:
            print(f"  [foot] terminal push skipped: {exc}", file=sys.stderr)
        return path
