"""GTK3/4 target — writes adw-gtk-theme colours to ``~/.config/gtk-{3,4}.0/colors.css``."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from .base import BaseTarget


def _hex(hex_str: str) -> str:
    """Strip the ``#`` prefix from a hex colour, or return as-is if bare."""
    return hex_str.lstrip("#")


class GtkTarget(BaseTarget):
    """Generate ``colors.css`` for both GTK3 and GTK4.

    The dotfiles import this file via:
      - GTK3: ``@import url('colors.css')`` in ``gtk-3.0/gtk.css``
      - GTK4: ``@import 'colors.css'`` in ``gtk-4.0/gtk.css``

    After writing, runs ``gsettings`` to apply the correct theme variant
    (``adw-gtk3`` / ``adw-gtk3-dark``) and colour scheme.
    """

    name = "gtk"
    description = "GTK3/4 adw-gtk-theme colours"
    output_path = "~/.config/gtk-3.0/colors.css"

    # ------------------------------------------------------------------
    # Render
    # ------------------------------------------------------------------

    def render(self, palette: dict, mode: str) -> str:
        colors = palette[mode]

        c4 = _hex(colors["c4"])
        on_c4 = _hex(colors["on_c4"])
        c2 = _hex(colors["c2"])
        on_c2 = _hex(colors["on_c2"])
        c1 = _hex(colors["c1"])
        on_c1 = _hex(colors["on_c1"])
        low = _hex(colors["low"])
        bottom = _hex(colors["bottom"])
        base = _hex(colors["base"])
        high = _hex(colors["high"])
        top = _hex(colors["top"])
        standard = _hex(colors["standard"])
        muted = _hex(colors["muted"])
        error = _hex(colors["error"])
        on_error = _hex(colors["on_error"])

        return f"""\
/*
 * GTK Colors
 * Generated by terratheme — Mode: {mode}
 */

/* ---------- adw-gtk-theme (GTK3) ---------- */
@define-color window_bg_color #{base};
@define-color window_fg_color #{standard};
@define-color view_bg_color #{base};
@define-color view_fg_color @window_fg_color;
@define-color accent_bg_color #{c4};
@define-color accent_fg_color #{on_c4};
@define-color accent_color @accent_bg_color;
@define-color headerbar_bg_color @window_bg_color;
@define-color headerbar_fg_color @window_fg_color;
@define-color headerbar_backdrop_color @window_bg_color;
@define-color headerbar_border_color @window_bg_color;
@define-color headerbar_shade_color @window_bg_color;
@define-color card_bg_color #{high};
@define-color card_fg_color @window_fg_color;
@define-color card_shade_color rgba(0, 0, 0, 0.07);
@define-color popover_bg_color #{top};
@define-color popover_fg_color @window_fg_color;
@define-color dialog_bg_color @card_bg_color;
@define-color dialog_fg_color @card_fg_color;
@define-color sidebar_bg_color @window_bg_color;
@define-color sidebar_fg_color @window_fg_color;
@define-color sidebar_backdrop_color @window_bg_color;
@define-color sidebar_shade_color rgba(0, 0, 0, 0.25);
@define-color secondary_sidebar_bg_color @window_bg_color;
@define-color secondary_sidebar_fg_color @window_fg_color;
@define-color secondary_sidebar_backdrop_color @window_bg_color;
@define-color secondary_sidebar_shade_color rgba(0, 0, 0, 0.25);
@define-color secondary_sidebar_border_color @window_bg_color;

@define-color warning_bg_color #{c2};
@define-color warning_fg_color #{on_c2};
@define-color warning_color #{c2};
@define-color error_bg_color #{error};
@define-color error_fg_color #{on_error};
@define-color error_color #{error};
@define-color success_bg_color #{c1};
@define-color success_fg_color #{on_c1};
@define-color success_color #{c1};
@define-color destructive_bg_color #{error};
@define-color destructive_fg_color #{on_error};
@define-color destructive_color #{error};

/* ---------- Standard GTK3 variables ---------- */
@define-color base_color #{base};
@define-color text_color #{standard};
@define-color insensitive_fg_color #{muted};
@define-color insensitive_bg_color #{base};
@define-color selected_fg_color #{on_c4};
@define-color selected_bg_color #{c4};
@define-color scrollbar_bg_color #{high};
@define-color scrollbar_slider_color #{c4};
@define-color tooltip_fg_color #{on_c4};
@define-color tooltip_bg_color #{top};
@define-color prelight_color #{c4};
@define-color menu_fg_color #{standard};
@define-color menu_bg_color #{base};
@define-color link_color #{c4};

/* ---------- CSS custom properties (GTK 4.16+) ---------- */
:root {{
    --accent-blue: #3584e4;
    --accent-teal: #2190a4;
    --accent-green: #3a944a;
    --accent-yellow: #c88800;
    --accent-orange: #ed5b00;
    --accent-red: #e62d42;
    --accent-pink: #d56199;
    --accent-purple: #9141ac;
    --accent-slate: #6f8396;

    --accent-bg-color: @accent_bg_color;
    --accent-fg-color: @accent_fg_color;

    --destructive-bg-color: @destructive_bg_color;
    --destructive-fg-color: @destructive_fg_color;

    --success-bg-color: @success_bg_color;
    --success-fg-color: @success_fg_color;

    --warning-bg-color: @warning_bg_color;
    --warning-fg-color: @warning_fg_color;

    --error-bg-color: @error_bg_color;
    --error-fg-color: @error_fg_color;

    --window-bg-color: @window_bg_color;
    --window-fg-color: @window_fg_color;

    --view-bg-color: @view_bg_color;
    --view-fg-color: @view_fg_color;

    --headerbar-bg-color: @headerbar_bg_color;
    --headerbar-fg-color: @headerbar_fg_color;
    --headerbar-border-color: @headerbar_border_color;
    --headerbar-backdrop-color: @headerbar_backdrop_color;
    --headerbar-shade-color: @headerbar_shade_color;

    --sidebar-bg-color: @sidebar_bg_color;
    --sidebar-fg-color: @sidebar_fg_color;
    --sidebar-backdrop-color: @sidebar_backdrop_color;
    --sidebar-border-color: @sidebar_border_color;
    --sidebar-shade-color: @sidebar_shade_color;

    --secondary-sidebar-bg-color: @secondary_sidebar_bg_color;
    --secondary-sidebar-fg-color: @secondary_sidebar_fg_color;
    --secondary-sidebar-backdrop-color: @secondary_sidebar_backdrop_color;
    --secondary-sidebar-border-color: @secondary_sidebar_border_color;
    --secondary-sidebar-shade-color: @secondary_sidebar_shade_color;

    --card-bg-color: @card_bg_color;
    --card-fg-color: @card_fg_color;
    --card-shade-color: @card_shade_color;

    --dialog-bg-color: @dialog_bg_color;
    --dialog-fg-color: @dialog_fg_color;

    --popover-bg-color: @popover_bg_color;
    --popover-fg-color: @popover_fg_color;
}}
"""

    # ------------------------------------------------------------------
    # Write — overridden to handle dual-path output + mode-aware hooks
    # ------------------------------------------------------------------

    def write(self, palette: dict, mode: str) -> Path:
        content = self.render(palette, mode)

        # Write GTK3
        path3 = Path(self.output_path).expanduser()
        path3.parent.mkdir(parents=True, exist_ok=True)
        path3.write_text(content)
        print(f"  {self.name}: {path3}", file=sys.stderr)

        # Write GTK4 (identical content)
        path4 = Path("~/.config/gtk-4.0/colors.css").expanduser()
        path4.parent.mkdir(parents=True, exist_ok=True)
        path4.write_text(content)
        print(f"  {self.name}: {path4}", file=sys.stderr)

        # Mode-aware gsettings hooks
        theme = "adw-gtk3" if mode == "light" else "adw-gtk3-dark"
        scheme = "default" if mode == "light" else "prefer-dark"

        cmds = [
            ["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", ""],
            ["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", theme],
            ["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme],
        ]
        for cmd in cmds:
            try:
                subprocess.run(cmd, check=False)
            except OSError as exc:
                print(f"  [{self.name}] hook failed: {exc}", file=sys.stderr)

        return path3
