"""Hyprland target — writes colour variables to ``~/.config/hypr/colors.conf``."""

from __future__ import annotations

from .base import BaseTarget


class HyprlandTarget(BaseTarget):
    """Generate ``~/.config/hypr/colors.conf`` with Terra DE v2 tokens.

    Used via ``source = ~/.config/hypr/colors.conf`` in ``hyprland.conf``.
    After writing, runs ``hyprctl reload`` so border colours apply immediately.
    """

    name = "hyprland"
    description = "Hyprland window manager colours (sourced as colors.conf)"
    output_path = "~/.config/hypr/colors.conf"

    # Tokens that are useful in a window-manager context.
    # The variable name **is** the v2 token name (with a ``$`` prefix per
    # Hyprlang syntax), making it obvious which palette value is being used.
    _TOKENS = (
        "c0",
        "c1",
        "c2",
        "c3",
        "c4",
        "base",
        "standard",
        "muted",
        "error",
    )

    def render(self, palette: dict, mode: str) -> str:
        colors = palette[mode]
        lines = [
            "# Generated by terratheme",
            f"# Mode: {mode}",
        ]
        for token in self._TOKENS:
            hex_no_hash = colors[token].lstrip("#")
            lines.append(f"${token} = rgb({hex_no_hash})")
        lines.append("")  # trailing newline
        return "\n".join(lines)

    def post_hook(self) -> list[str]:
        return ["hyprctl reload 2>/dev/null || true"]
