"""lf targets — file-type colours and prompt colours."""

from __future__ import annotations

from .base import BaseTarget


# ---------------------------------------------------------------------------
# File-type entries:   (pattern,  bold, token)
# ---------------------------------------------------------------------------
_FILE_TYPES: list[tuple[str, bool, str]] = [
    ("ln",  False, "c2"),       # symlink
    ("or",  False, "error"),    # orphan / broken link
    ("tw",  False, "c0"),       # sticky directory, world-writable
    ("ow",  False, "c0"),       # sticky directory, other-writable
    ("st",  False, "c4"),       # sticky bit
    ("di",  True,  "c4"),       # directory
    ("pi",  False, "c3"),       # named pipe
    ("so",  False, "c3"),       # socket
    ("bd",  False, "c0"),       # block device
    ("cd",  False, "c0"),       # character device
    ("su",  True,  "error"),    # setuid
    ("sg",  True,  "error"),    # setgid
    ("ex",  True,  "c3"),       # executable
    ("fi",  False, "standard"), # regular file
]

# ---------------------------------------------------------------------------
# Extension-group entries:   (glob, token)
# ---------------------------------------------------------------------------
_EXT_GROUPS: list[tuple[str, str, list[str]]] = [
    ("# Archives",   "error", [
        "*.7z", "*.bz2", "*.gz", "*.tar", "*.tbz2", "*.tgz",
        "*.txz", "*.xz", "*.zip", "*.rar",
    ]),
    ("# Images",     "c4",    [
        "*.gif", "*.ico", "*.jpg", "*.jpeg", "*.png", "*.svg", "*.webp",
    ]),
    ("# Audio",      "c2",    [
        "*.flac", "*.m4a", "*.mp3", "*.ogg", "*.opus", "*.wav", "*.wma",
    ]),
    ("# Video",      "c3",    [
        "*.avi", "*.flv", "*.mkv", "*.mov", "*.mp4", "*.webm", "*.wmv",
    ]),
]


def _rgb(hex_str: str) -> tuple[int, int, int]:
    """Parse ``#ff8000`` to ``(255, 128, 0)``."""
    h = hex_str.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _ansi(hex_str: str, bold: bool = False) -> str:
    """Build the ANSI prefix for an lf colour entry."""
    r, g, b = _rgb(hex_str)
    mod = "01;" if bold else ""
    return f"{mod}38;2;{r};{g};{b}"


class LfTarget(BaseTarget):
    """File-type colour definitions for lf (auto-loaded from ``~/.config/lf/colors``)."""

    name = "lf"
    description = "lf file manager file-type colours"
    output_path = "~/.config/lf/colors"

    def render(self, palette: dict, mode: str) -> str:
        colors = palette[mode]
        lines: list[str] = [
            "# Generated by terratheme",
            f"# Mode: {mode}",
            "",
            "# File types",
        ]

        for pattern, bold, token in _FILE_TYPES:
            ansi = _ansi(colors[token], bold=bold)
            lines.append(f"{pattern:8s}{ansi}")

        for header, token, exts in _EXT_GROUPS:
            lines.append("")
            lines.append(header)
            for ext in exts:
                ansi = _ansi(colors[token])
                lines.append(f"{ext:12s}{ansi}")

        lines.append("")
        return "\n".join(lines)


class LfPromptTarget(BaseTarget):
    """lf prompt colour string (sourced as ``prompt-colors`` from ``lfrc``)."""

    name = "lf-prompt"
    description = "lf file manager prompt colours"
    output_path = "~/.config/lf/prompt-colors"

    def render(self, palette: dict, mode: str) -> str:
        colors = palette[mode]
        r1, g1, b1 = _rgb(colors["c4"])
        r2, g2, b2 = _rgb(colors["c2"])
        return (
            '# Generated by terratheme\n'
            f'set promptfmt '
            f'"\\033[1;38;2;{r1};{g1};{b1}m%u@%h\\033[0m'
            f':\\033[1;38;2;{r2};{g2};{b2}m%d\\033[0m"\n'
        )
