"""Zellij target — writes a KDL colour theme to ``~/.config/zellij/themes/matugen.kdl``."""

from __future__ import annotations

from .base import BaseTarget


# Each entry: (base_token, bg_token, em0, em1, em2, em3)
# bg_token=0 means literal "0" (transparent).
_GROUPS: dict[str, tuple[str | int, ...]] = {
    "text_unselected":        ("muted",    "base", "c4", "c2", "c1", "c0"),
    "text_selected":          ("standard", "high", "c4", "c2", "c1", "c0"),
    "ribbon_unselected":      ("standard", "low",  "c4", "base", "c4", "c4"),
    "ribbon_selected":        ("standard", "c4",   "c2", "c1",   "c0", "c0"),
    "table_title":            ("c4",       "base", "c4", "c2", "c1", "c0"),
    "table_cell_unselected":  ("standard", "base", "c4", "c2", "c1", "c0"),
    "table_cell_selected":    ("standard", "high",  "standard", "standard", "standard", "standard"),
    "list_unselected":        ("standard", "base", "c4", "c2", "c1", "c0"),
    "list_selected":          ("standard", "high", "standard", "standard", "standard", "standard"),
    "frame_unselected":       ("outline",  0,      "c4", "c2", "c1", "c0"),
    "frame_selected":         ("c4",       0,      "c2", "c0", "c0", "c0"),
    "frame_highlight":        ("c3",       0,      "c2", "c0", "c0", "c0"),
    "exit_code_success":      ("c0",       0,      "c4", "c2", "c1", "c0"),
    "exit_code_error":        ("error",    0,      "c4", "c2", "c1", "c0"),
}


_SLOT_NAMES = ("base", "background", "emphasis_0", "emphasis_1", "emphasis_2", "emphasis_3")


def _rgb(hex_str: str) -> str:
    """Convert a hex colour like ``#ff8000`` to ``\"255 128 0\"``."""
    h = hex_str.lstrip("#")
    r = int(h[0:2], 16)
    g = int(h[2:4], 16)
    b = int(h[4:6], 16)
    return f"{r} {g} {b}"


class ZellijTarget(BaseTarget):
    """Generate a Zellij theme at ``~/.config/zellij/themes/matugen.kdl``.

    The dotfiles reference ``theme \"matugen\"`` in ``config.kdl``, so this
    target writes to the same path with the same theme-block name.
    """

    name = "zellij"
    description = "Zellij terminal multiplexer theme"
    output_path = "~/.config/zellij/themes/matugen.kdl"

    def render(self, palette: dict, mode: str) -> str:
        colors = palette[mode]
        lines = [
            "// Generated by terratheme",
            f"// Mode: {mode}",
            "",
            "themes {",
            "    matugen {",
        ]

        for group_name, tokens in _GROUPS.items():
            lines.append(f"        {group_name} {{")
            for slot, token in zip(_SLOT_NAMES, tokens):
                if token == 0:
                    value = "0"
                else:
                    value = _rgb(colors[str(token)])
                lines.append(f"            {slot} {value}")
            lines.append("        }")

        lines.append("    }")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def post_hook(self) -> list[str]:
        return ["touch ~/.config/zellij/config.kdl"]
